[package]
name = "possum2-emu"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
termion = "2"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4", features = ["derive"] }
